name: yoga_challenge_flutter
description: A Flutter version of the Yoga Challenge app with ManyChat integration and video streaming capabilities.

publish_to: 'none'

version: 1.1.34+34

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Requests
  http: ^1.1.0
  dio: ^5.4.0  # Alternative HTTP client for iOS networking issues
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Video Player
  video_player: ^2.8.1
  chewie: ^1.7.4
  webview_flutter: ^4.4.2
  
  # Notifications (temporarily disabled for APK build)
  # flutter_local_notifications: ^16.3.0
  # timezone: ^0.9.2
  
  # Permissions
  permission_handler: ^11.0.1
  
  # URL Launcher
  url_launcher: ^6.2.1
  
  # Date/Time
  intl: ^0.18.1
  
  # JSON
  json_annotation: ^4.8.1
  
  # Background Tasks
  workmanager: ^0.5.2
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Loading
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/favicon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/data/yoga_messages.json
    - assets/images/
  
  # Using Google Fonts instead of local font files
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
